services:
  postgres:
    image: bitnami/postgresql:latest
    restart: always
    networks:
      - minha_rede
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=meu_guru
      - DATABASE_URL="postgresql://postgres:123456@postgres:5432/meu_guru?schema=public"
    container_name: postgres
    volumes:
      - meu_guru_data:/bitnami/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d meu_guru"]
      timeout: 5s
      retries: 5
  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 3000:3000
    working_dir: /app-backend
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: npx prisma migrate dev --name init --schema=./prisma/schema.prisma && npm run start:dev
    networks:
      - minha_rede
    environment:
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/meu_guru?schema=public  
    volumes: 
      - ./backend/src:/app-backend/src
      - ./backend/prisma:/app-backend/prisma
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"] 
      timeout: 10s
      retries: 5
   # frontend:
  #   container_name: app_frontend
  #   build: ./frontend
  #   ports:
  #     - 3001:3001
  #   working_dir: /app-frontend
  #   volumes: 
  #     - ./frontend/src:/app-frontend/src
  #   command: dev
  #   healthcheck:
  #     test: ["CMD", "lsof", "-t", "-i:3001"] 
  #     timeout: 10s
  #     retries: 5
  #   depends_on:
  #     - backend

networks:
  minha_rede:
    driver: bridge
volumes:
  meu_guru_data: 
