
version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app_backend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    command: start:dev
    volumes: 
      - ./backend/src:/app-backend/src
      - ./backend/prisma:/app-backend/prisma
    networks:
      - guru_network
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: postgresprisma
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - guru_network
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - 3001:3001
    volumes: 
      - ./frontend/src:/app-frontend/src
    command: dev
    depends_on:
      - backend
    networks:
      - guru_network
volumes:
  postgres:
    name: meu-guru-data
networks:
  guru_network:
    name: meu_guru_network
    driver: bridge